### ISSUE TITLE
Error 400 Unable to authenticate

### ISSUE THREAD

**Issue by kavehv** [ohmantics/homebridge-airmega#60] opened 2024-06-02 04:29 UTC
I’m running into this error and I can’t seem to connect to Coway anymore with this plugin.  I’m curious if anyone else is running into this issue.

>[6/1/2024, 9:24:30 PM] [Airmega] [ERROR] Unable to authenticate. 400 - "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"  \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" class=\"\">\n\n<head>\n    <title>Coway - Login</title>\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n    <meta name=\"format-detection\" content=\"telephone=no, address=no, email=no\">\n\n    <meta name=\"title\" content=\"coway\">\n    <meta name=\"keywords\" content=\"coway\">\n    <meta name=\"description\" content=\"coway\">\n\n    <meta property=\"og:title\" content=\"coway\">\n    <meta property=\"og:type\" content=\"website\">\n    <meta property=\"og:url\" content=\"coway\">\n    <meta property=\"og:site_name\" content=\"coway\">\n    <meta property=\"og:description\" content=\"coway\">\n    <meta charset=\"utf-8\">\n\n    <meta name=\"robots\" content=\"noindex, nofollow\">\n\n    \n    <script\n            async\n            src=\"https://www.googletagmanager.com/gtag/js?id=G-67LG8PXDQZ\"\n    ></script>\n    <script>\n        window.dataLayer = window.dataLayer || []\n        function gtag() {\n            dataLayer.push(arguments)\n        }\n        gtag('js', new Date())\n\n        gtag('config', 'G-67LG8PXDQZ', {\n            send_page_view: false,\n        })\n    </script>\n\n    \n    <script async>\n        ;(function (w, d, s, l, i) {\n            w[l] = w[l] || []\n            w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' })\n            var f = d.getElementsByTagName(s)[0],\n                j = d.createElement(s),\n                dl = l != 'dataLayer' ? '&l=' + l : ''\n            j.async = true\n            j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl\n            f.parentNode.insertBefore(j, f)\n        })(window, document, 'script', 'dataLayer', 'GTM-NRTM7JZ')\n    </script>\n\n    \n\n\n\n\n            <link href=\"/auth/resources/aj0g8/login/cw-account/css/common.css?ver=202400150454\" rel=\"stylesheet\" />\n            <link href=\"/auth/resources/aj0g8/login/cw-account/css/member.css?ver=202400150454\" rel=\"stylesheet\" />\n            <link href=\"/auth/resources/aj0g8/login/cw-account/css/account.css?ver=202400150454\" rel=\"stylesheet\" />\n            <link href=\"/auth/resources/aj0g8/login/cw-account/css/login.css?ver=202400150454\" rel=\"stylesheet\" />\n            <script src=\"/auth/resources/aj0g8/login/cw-account/js/jquery-3.6.0.min.js?ver=202400150454\" type=\"text/javascript\"></script>\n            <script src=\"/auth/resources/aj0g8/login/cw-account/js/core-js.3.21.1.min.js?ver=202400150454\" type=\"text/javascript\"></script>\n            <script src=\"/auth/resources/aj0g8/login/cw-account/js/ui.js?ver=202400150454\" type=\"text/javascript\"></script>\n            <script src=\"/auth/resources/aj0g8/login/cw-account/js/common.js?ver=202400150454\" type=\"text/javascript\"></script>\n            <script src=\"/auth/resources/aj0g8/login/cw-account/js/ga-utils.js?ver=202400150454\" type=\"text/javascript\"></script>\n\n\n</head>\n\n<body class=\"\">\n<div id=\"wrap\" class=\"\">\n    \n\n\n\n    \n    <input type=\"hidden\" id=\"loginOnly\" name=\"loginOnly\" value=\"false\"/>\n    <input type=\"hidden\" id=\"clientName\" value=\"\"/>\n    \n    \n    <header id=\"member_header\" class=\"\">\n        <input type=\"hidden\" id=\"currentLocaleTag\" name=\"currentLocaleTag\" value=\"en\" />\n        <input type=\"hidden\" id=\"currentLocale\" name=\"currentLocale\" value=\"English\" />\n        \n        <div class=\"h_container\">\n            <a href=\"#\" class=\"page_depth\">Page back</a>\n        </div>\n    </header>\n    \n\n    \n    <div id=\"container\" class=\"\">\n        <div id=\"kc-error-message\">\n            <p class=\"instruction\">Client disabled.</p>\n        </div>\n    </div>\n    \n\n    \n    \n</div>\n</body>\n</html>\n"

**Comment by akeybl** [comment] 2024-06-04 17:57
Happening to me as well. Let me know how I can help.

**Comment by nbraunstein** [comment] 2024-06-07 02:55
Happening to me too.

**Comment by archcorsair** [comment] 2024-06-07 19:28
Happening to me as well, `Client disabled.` error

**Comment by nbraunstein** [comment] 2024-06-07 20:16
Here is my error when trying to login. 


[Airmega] [ERROR] Unable to authenticate. 400 - "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"  \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" class=\"\">\n\n<head>\n    <title>Coway - Login</title>\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n    <meta name=\"format-detection\" content=\"telephone=no, address=no, email=no\">\n\n    <meta name=\"title\" content=\"coway\">\n    <meta name=\"keywords\" content=\"coway\">\n    <meta name=\"description\" content=\"coway\">\n\n    <meta property=\"og:title\" content=\"coway\">\n    <meta property=\"og:type\" content=\"website\">\n    <meta property=\"og:url\" content=\"coway\">\n    <meta property=\"og:site_name\" content=\"coway\">\n    <meta property=\"og:description\" content=\"coway\">\n    <meta charset=\"utf-8\">\n\n    <meta name=\"robots\" content=\"noindex, nofollow\">\n\n    \n    <script\n            async\n            src=\"https://www.googletagmanager.com/gtag/js?id=G-67LG8PXDQZ\"\n    ></script>\n    <script>\n        window.dataLayer = window.dataLayer || []\n        function gtag() {\n            dataLayer.push(arguments)\n        }\n        gtag('js', new Date())\n\n        gtag('config', 'G-67LG8PXDQZ', {\n            send_page_view: false,\n        })\n    </script>\n\n    \n    <script async>\n        ;(function (w, d, s, l, i) {\n            w[l] = w[l] || []\n            w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' })\n            var f = d.getElementsByTagName(s)[0],\n                j = d.createElement(s),\n                dl = l != 'dataLayer' ? '&l=' + l : ''\n            j.async = true\n            j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl\n            f.parentNode.insertBefore(j, f)\n        })(window, document, 'script', 'dataLayer', 'GTM-NRTM7JZ')\n    </script>\n\n    \n\n\n\n\n            <link href=\"/auth/resources/aj0g8/login/cw-account/css/common.css?ver=202400150454\" rel=\"stylesheet\" />\n            <link href=\"/auth/resources/aj0g8/login/cw-account/css/member.css?ver=202400150454\" rel=\"stylesheet\" />\n            <link href=\"/auth/resources/aj0g8/login/cw-account/css/account.css?ver=202400150454\" rel=\"stylesheet\" />\n            <link href=\"/auth/resources/aj0g8/login/cw-account/css/login.css?ver=202400150454\" rel=\"stylesheet\" />\n            <script src=\"/auth/resources/aj0g8/login/cw-account/js/jquery-3.6.0.min.js?ver=202400150454\" type=\"text/javascript\"></script>\n            <script src=\"/auth/resources/aj0g8/login/cw-account/js/core-js.3.21.1.min.js?ver=202400150454\" type=\"text/javascript\"></script>\n            <script src=\"/auth/resources/aj0g8/login/cw-account/js/ui.js?ver=202400150454\" type=\"text/javascript\"></script>\n            <script src=\"/auth/resources/aj0g8/login/cw-account/js/common.js?ver=202400150454\" type=\"text/javascript\"></script>\n            <script src=\"/auth/resources/aj0g8/login/cw-account/js/ga-utils.js?ver=202400150454\" type=\"text/javascript\"></script>\n\n\n</head>\n\n<body class=\"\">\n<div id=\"wrap\" class=\"\">\n    \n\n\n\n    \n    <input type=\"hidden\" id=\"loginOnly\" name=\"loginOnly\" value=\"false\"/>\n    <input type=\"hidden\" id=\"clientName\" value=\"\"/>\n    \n    \n    <header id=\"member_header\" class=\"\">\n        <input type=\"hidden\" id=\"currentLocaleTag\" name=\"currentLocaleTag\" value=\"en\" />\n        <input type=\"hidden\" id=\"currentLocale\" name=\"currentLocale\" value=\"English\" />\n        \n        <div class=\"h_container\">\n            <a href=\"#\" class=\"page_depth\">Page back</a>\n        </div>\n    </header>\n    \n\n    \n    <div id=\"container\" class=\"\">\n        <div id=\"kc-error-message\">\n            <p class=\"instruction\">Client disabled.</p>\n        </div>\n    </div>\n    \n\n    \n    \n</div>\n</body>\n</html>\n"

**Comment by BastianZim** [comment] 2024-06-10 19:37
Also got a `Unable to authenticate. 400` error

**Comment by ohmantics** [comment] 2024-06-10 20:07
Duplicate of #59

**Closed as completed** 2024-06-10 20:07 UTC
